name: testing
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print outout
        run: echo "hello world"
      - name: print bye
        run: echo "byee"
      - name: testing new changes
        run: echo "changing from VS code"
