name: newworkflow_tetsing
on: [workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: get data
        run: echo "${{ toJSON(github) }}"
      - name: print bye
        run: ps -eaf 
      - name: testing new changes
        run: echo "changing from VS code"
      - name: testing again new changes
        run: echo "from VS code"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: print outout
        run: echo "hello world"
  second2-job:
    needs: [first-job,second-job] 
    runs-on: ubuntu-latest
    steps:
      - name: print outout
        run: echo "hello world2"

